apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-leases
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: security
  - kind: ServiceAccount
    name: cert-manager-cainjector
    namespace: security
  - kind: ServiceAccount
    name: cert-manager-webhook
    namespace: security
roleRef:
  kind: ClusterRole
  name: cert-manager-leases
  apiGroup: rbac.authorization.k8s.io
