apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.24.2
    releaseName: istio-base
    namespace: istio-system
    valuesInline:
      defaultRevision: default

  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.24.2
    releaseName: istiod
    namespace: istio-system
    valuesInline:
      pilot:
        resources:
          requests:
            cpu: 500m
            memory: 2048Mi

  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.24.2
    releaseName: istio-ingress
    namespace: istio-ingress
    valuesInline:
      service:
        type: LoadBalancer
