apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: '${SMTP_SMARTHOST}'
      smtp_from: '${SMTP_FROM}'
      smtp_auth_username: '${SMTP_AUTH_USERNAME}'
      smtp_auth_password: '${SMTP_AUTH_PASSWORD}'
      smtp_require_tls: true

    route:
      receiver: 'email-alerts'

    receivers:
    - name: 'email-alerts'
      email_configs:
      - to: '${RECIPIENT_EMAIL}'

