apiVersion: apps/v1
kind: Deployment
metadata:
  name: coder
spec:
  template:
    spec:
      containers:
        - name: coder
          image: coder/coder:latest
          env:
            - name: CODER_PG_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: coder-db-url
                  key: url
