apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

secretGenerator:
  - name: grafana-secret
    envs:
      - .env
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 8.8.6
    releaseName: grafana
    namespace: monitoring
    valuesFile: values.yaml
