apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'email-alerts'
    receivers:
      - name: 'email-alerts'
        email_configs:
          - to: '${RECIPIENT_EMAIL}'
            from: '${SMTP_FROM}'
            smarthost: '${SMTP_SMARTHOST}'
            auth_username: '${SMTP_AUTH_USERNAME}'
            auth_password: '${SMTP_AUTH_PASSWORD}'

