apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 68.4.4
    releaseName: prometheus
    namespace: monitoring
    valuesFile: values.yaml
