apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-prometheus-access
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: monitoring
roleRef:
  kind: Role
  name: prometheus-access
  apiGroup: rbac.authorization.k8s.io

