apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
  - namespace.yaml

secretGenerator:
  - name: minio-creds
    envs:
      - .env
    options:
      disableNameSuffixHash: true

helmCharts:
  - name: minio
    repo: https://charts.min.io/
    version: 5.4.0
    releaseName: minio
    namespace: minio
    valuesFile: values.yaml
