apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

secretGenerator:
  - name: tempo-creds
    envs:
      - .env
    options:
      disableNameSuffixHash: true

helmCharts:
  - name: tempo-distributed
    repo: https://grafana.github.io/helm-charts
    version: 1.32.0
    releaseName: tempo-distributed
    namespace: monitoring
    valuesFile: values.yaml
